// Same ActivitySnapshot v1 fixtures feed every layout. No task outcomes or transcripts.
const now = Date.now();
export const workspaces = [
  ['projects', 'Projects'],
  ['commerce', 'Commerce platform'],
  ['infra', 'Infrastructure'],
  ['docs', 'Developer documentation'],
  ['mobile', 'Mobile companion'],
  ['research', 'Research / retrieval experiments'],
  ['design', 'Design system'],
  ['payments', 'Payments'],
  [
    'archive',
    'Archived migration investigation — compatibility for older enterprise tenants',
  ],
  ['shells', 'Local tooling'],
  ['empty', 'Weekend ideas'],
  ['sandbox', 'Sandbox'],
].map(([id, name]) => ({ id, name }));
const rows = [
  [
    'projects',
    'herdr-manager',
    'Review activity layout alternatives',
    'Codex',
    'working',
    null,
    4,
  ],
  [
    'projects',
    'herdr-plugin',
    'Waiting for permission to inspect local socket',
    'Claude',
    'blocked',
    null,
    45,
  ],
  [
    'commerce',
    'storefront',
    'Checkout address validation needs a product decision',
    'Codex',
    'blocked',
    null,
    125,
  ],
  [
    'infra',
    'terraform-live',
    'Network policy review',
    'Claude',
    'idle',
    'turn-ended',
    16,
  ],
  [
    'docs',
    'developer-docs',
    'Restructure installation guide',
    'Codex',
    'idle',
    'turn-ended',
    29,
  ],
  [
    'mobile',
    'ios-companion',
    'Investigate background refresh behavior',
    'Claude',
    'working',
    null,
    8,
  ],
  [
    'research',
    'retrieval-experiments',
    'Compare ranking strategies',
    'Codex',
    'working',
    null,
    12,
  ],
  [
    'design',
    'interface-foundations',
    'Token naming exploration',
    'Claude',
    'working',
    null,
    22,
  ],
  [
    'payments',
    'billing-service',
    'Reconcile subscription state',
    'Codex',
    'working',
    null,
    31,
  ],
  [
    'archive',
    'enterprise-tenant-compatibility-and-data-migration',
    'Investigate legacy redirect behavior across regional tenant environments with custom identity providers',
    'Other',
    'unknown',
    null,
    null,
  ],
  [
    'projects',
    'shared-model',
    'Observer contract notes',
    'Codex',
    'idle',
    null,
    850,
  ],
  ['sandbox', 'playground', 'Untitled agent', 'Other', 'unknown', null, null],
  [
    'commerce',
    'storefront',
    'Accessibility review — secondary attachment',
    'Claude',
    'idle',
    null,
    410,
  ],
  ['shells', 'local-tools', 'zsh · local tooling', null, 'unknown', null, null],
  ['shells', 'local-tools', 'npm logs', null, 'unknown', null, null],
  [
    'projects',
    'herdr-manager',
    'zsh · preview server',
    null,
    'unknown',
    null,
    null,
  ],
];
export const demo = {
  version: 1,
  revision: 42,
  endpoint: 'demo://daylight-desk',
  connection: { state: 'connected', lastSuccessAt: now, error: null },
  workspaces,
  panes: rows.map(
    ([workspaceId, repo, title, agent, rawStatus, attention, age], i) => ({
      id: `pane-${i + 1}`,
      workspaceId,
      title,
      cwd: `/work/${repo}`,
      agent,
      sessionId: agent ? `session-${i === 12 ? 2 : i}` : null,
      rawStatus,
      reportedStatus: agent ? rawStatus : null,
      attention,
      lastActivityAt: age === null ? null : now - age * 1000,
    })
  ),
};
export function fixture(scenario) {
  return {
    ...demo,
    connection:
      scenario === 'disconnected'
        ? {
            state: 'disconnected',
            lastSuccessAt: now - 184000,
            error: 'Demo: socket connection lost; inventory retained.',
          }
        : demo.connection,
  };
}
